coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 85%
        threshold: 5%

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false 