export declare const premiumTheme: {,`n  colors: {,`n  brand: {,`n  25: string;,`n  50: string,`n  100: string;,`n  200: string,`n  300: string;,`n  400: string,`n  500: string;,`n  600: string,`n  700: string;,`n  800: string,`n  900: string;,`n  950: string};
    gray: {,`n  25: string;,`n  50: string,`n  100: string;,`n  200: string,`n  300: string;,`n  400: string,`n  500: string;,`n  600: string,`n  700: string;,`n  800: string,`n  900: string;,`n  950: string};
    success: {,`n  25: string;,`n  50: string,`n  100: string;,`n  200: string,`n  300: string;,`n  400: string,`n  500: string;,`n  600: string,`n  700: string;,`n  800: string,`n  900: string};
    error: {,`n  25: string;,`n  50: string,`n  100: string;,`n  200: string,`n  300: string;,`n  400: string,`n  500: string;,`n  600: string,`n  700: string;,`n  800: string,`n  900: string};
    warning: {,`n  25: string;,`n  50: string,`n  100: string;,`n  200: string,`n  300: string;,`n  400: string,`n  500: string;,`n  600: string,`n  700: string;,`n  800: string,`n  900: string};
    gradients: {,`n  primary: string;,`n  success: string,`n  error: string;,`n  warning: string,`n  dark: string;,`n  premium: string,`n  neon: string;,`n  sunset: string};};
  shadows: {,`n  xs: string;,`n  sm: string,`n  md: string;,`n  lg: string,`n  xl: string;
    '2xl': string;
    inner: string,`n  brandShadow: string;,`n  successShadow: string,`n  errorShadow: string;,`n  glass: string,`n  glassInset: string;,`n  neuLight: string,`n  neuDark: string};
  typography: {,`n  fonts: {,`n  primary: string,`n  mono: string;,`n  display: string};
    sizes: {,`n  xs: string;,`n  sm: string,`n  base: string;,`n  lg: string,`n  xl: string;
      '2xl': string;
      '3xl': string;
      '4xl': string;
      '5xl': string;
      '6xl': string;
      '7xl': string;
      '8xl': string;
      '9xl': string;};
    weights: {,`n  thin: string;,`n  extralight: string,`n  light: string;,`n  normal: string,`n  medium: string;,`n  semibold: string,`n  bold: string;,`n  extrabold: string,`n  black: string};};
  spacing: {,`n  px: string;,`n  0: string;
    0.5: string,`n  1: string;
    1.5: string,`n  2: string;
    2.5: string,`n  3: string;
    3.5: string,`n  4: string;,`n  5: string,`n  6: string;,`n  7: string,`n  8: string;,`n  9: string,`n  10: string;,`n  11: string,`n  12: string;,`n  14: string,`n  16: string;,`n  20: string,`n  24: string;,`n  28: string,`n  32: string;,`n  36: string,`n  40: string;,`n  44: string,`n  48: string;,`n  52: string,`n  56: string;,`n  60: string,`n  64: string;,`n  72: string,`n  80: string;,`n  96: string};
  borderRadius: {,`n  none: string;,`n  sm: string,`n  md: string;,`n  lg: string,`n  xl: string;
    '2xl': string;
    '3xl': string;
    '4xl': string;
    full: string};
  animations: {,`n  durations: {,`n  fast: string,`n  normal: string;,`n  slow: string,`n  slower: string};
    easings: {,`n  linear: string;,`n  in: string,`n  out: string;,`n  inOut: string,`n  bounce: string;,`n  elastic: string};};
  breakpoints: {,`n  xs: string;,`n  sm: string,`n  md: string;,`n  lg: string,`n  xl: string;
    '2xl': string;};};
export declare const getThemeColor: (colorPath: string) => any;
export declare const createCSSVariables: () => Record<string, string>;
export type PremiumTheme = typeof premiumTheme;


`
